### ISSUE TITLE
老哥能出个自己制作接口的教程吗，或者哪里可以学习呢，编程小白

### ISSUE THREAD

**Issue by Leexiaolong** [liu673cn/mao#9]
英文略懂，想自己选一些稳定流畅的接口自己家里用。但是不太懂里面的意思。大概看了下json或txt文件，分成点播和直播两个部分。点播的格式都一样，但是最前面一般有一个爬虫的jar文件，这个文件啥作用，怎么制作，求教程

**Comment by ldb2004** [comment]
同求啊。我想制作一个好接口分享给大家。

**Comment by liu673cn** [comment]
https://github.com/CatVodTVOfficial/

**Comment by ldb2004** [comment]
> https://github.com/CatVodTVOfficial/

老哥在线。那个编辑器一直是请稍后。。

**Comment by liu673cn** [comment]
https://liu673cn.github.io/mao/sub/xpath套娃.json

https://liu673cn.github.io/mao/sub/biubiu套娃.json
